//! Theme color definitions for the TUI.
//!
//! Extracted from `app.rs` (Step 0 of the foundation refactor). Pure code move —
//! no behavior change. Holds the `ThemeColors` struct and the 7 named themes.

#[derive(Clone, Copy)]
pub struct ThemeColors {
    pub bg: ratatui::style::Color,
    pub fg: ratatui::style::Color,
    pub accent: ratatui::style::Color,
    pub border: ratatui::style::Color,
    pub border_active: ratatui::style::Color,
    pub highlight: ratatui::style::Color,
    pub highlight_fg: ratatui::style::Color,
    pub message_user: ratatui::style::Color,
    pub message_assistant: ratatui::style::Color,
    pub message_system: ratatui::style::Color,
    pub status_bg: ratatui::style::Color,
    pub status_fg: ratatui::style::Color,
}

impl ThemeColors {
    pub fn get(name: &str) -> Self {
        match name {
            "midnight" => Self {
                bg: ratatui::style::Color::Rgb(15, 17, 26),
                fg: ratatui::style::Color::Rgb(230, 230, 230),
                accent: ratatui::style::Color::Magenta,
                border: ratatui::style::Color::Rgb(60, 60, 80),
                border_active: ratatui::style::Color::Magenta,
                highlight: ratatui::style::Color::Magenta,
                highlight_fg: ratatui::style::Color::White,
                message_user: ratatui::style::Color::Magenta,
                message_assistant: ratatui::style::Color::Cyan,
                message_system: ratatui::style::Color::DarkGray,
                status_bg: ratatui::style::Color::Rgb(30, 30, 50),
                status_fg: ratatui::style::Color::Rgb(200, 200, 220),
            },
            "forest" => Self {
                bg: ratatui::style::Color::Rgb(15, 29, 20),
                fg: ratatui::style::Color::Rgb(233, 245, 234),
                accent: ratatui::style::Color::Green,
                border: ratatui::style::Color::Rgb(40, 70, 40),
                border_active: ratatui::style::Color::Green,
                highlight: ratatui::style::Color::Green,
                highlight_fg: ratatui::style::Color::Black,
                message_user: ratatui::style::Color::Green,
                message_assistant: ratatui::style::Color::Yellow,
                message_system: ratatui::style::Color::DarkGray,
                status_bg: ratatui::style::Color::Rgb(20, 40, 25),
                status_fg: ratatui::style::Color::Rgb(200, 230, 200),
            },
            "terminal" => Self {
                bg: ratatui::style::Color::Rgb(0, 17, 0),
                fg: ratatui::style::Color::Rgb(128, 255, 128),
                accent: ratatui::style::Color::Rgb(128, 255, 128),
                border: ratatui::style::Color::Rgb(0, 64, 0),
                border_active: ratatui::style::Color::Rgb(128, 255, 128),
                highlight: ratatui::style::Color::Rgb(0, 128, 0),
                highlight_fg: ratatui::style::Color::Black,
                message_user: ratatui::style::Color::Rgb(255, 255, 255),
                message_assistant: ratatui::style::Color::Rgb(128, 255, 128),
                message_system: ratatui::style::Color::Rgb(0, 128, 0),
                status_bg: ratatui::style::Color::Rgb(0, 30, 0),
                status_fg: ratatui::style::Color::Rgb(128, 255, 128),
            },
            "dracula" => Self {
                bg: ratatui::style::Color::Rgb(40, 42, 54),
                fg: ratatui::style::Color::Rgb(248, 248, 242),
                accent: ratatui::style::Color::Rgb(255, 121, 198),
                border: ratatui::style::Color::Rgb(68, 71, 90),
                border_active: ratatui::style::Color::Rgb(255, 121, 198),
                highlight: ratatui::style::Color::Rgb(189, 147, 249),
                highlight_fg: ratatui::style::Color::Rgb(40, 42, 54),
                message_user: ratatui::style::Color::Rgb(255, 121, 198),
                message_assistant: ratatui::style::Color::Rgb(80, 250, 123),
                message_system: ratatui::style::Color::Rgb(98, 114, 164),
                status_bg: ratatui::style::Color::Rgb(30, 31, 41),
                status_fg: ratatui::style::Color::Rgb(248, 248, 242),
            },
            "solarized" => Self {
                bg: ratatui::style::Color::Rgb(0, 43, 54),
                fg: ratatui::style::Color::Rgb(131, 148, 150),
                accent: ratatui::style::Color::Rgb(38, 139, 210),
                border: ratatui::style::Color::Rgb(7, 54, 66),
                border_active: ratatui::style::Color::Rgb(38, 139, 210),
                highlight: ratatui::style::Color::Rgb(42, 161, 152),
                highlight_fg: ratatui::style::Color::Rgb(0, 43, 54),
                message_user: ratatui::style::Color::Rgb(38, 139, 210),
                message_assistant: ratatui::style::Color::Rgb(133, 153, 0),
                message_system: ratatui::style::Color::Rgb(88, 110, 117),
                status_bg: ratatui::style::Color::Rgb(0, 30, 38),
                status_fg: ratatui::style::Color::Rgb(147, 161, 161),
            },
            "nord" => Self {
                bg: ratatui::style::Color::Rgb(46, 52, 64),
                fg: ratatui::style::Color::Rgb(216, 222, 233),
                accent: ratatui::style::Color::Rgb(136, 192, 208),
                border: ratatui::style::Color::Rgb(59, 66, 82),
                border_active: ratatui::style::Color::Rgb(136, 192, 208),
                highlight: ratatui::style::Color::Rgb(94, 129, 172),
                highlight_fg: ratatui::style::Color::Rgb(236, 239, 244),
                message_user: ratatui::style::Color::Rgb(136, 192, 208),
                message_assistant: ratatui::style::Color::Rgb(163, 190, 140),
                message_system: ratatui::style::Color::Rgb(97, 108, 135),
                status_bg: ratatui::style::Color::Rgb(36, 41, 51),
                status_fg: ratatui::style::Color::Rgb(216, 222, 233),
            },
            // "ocean" and default
            _ => Self {
                bg: ratatui::style::Color::Rgb(11, 27, 43),
                fg: ratatui::style::Color::Rgb(234, 244, 255),
                accent: ratatui::style::Color::Cyan,
                border: ratatui::style::Color::Rgb(40, 60, 80),
                border_active: ratatui::style::Color::Cyan,
                highlight: ratatui::style::Color::Cyan,
                highlight_fg: ratatui::style::Color::Black,
                message_user: ratatui::style::Color::Cyan,
                message_assistant: ratatui::style::Color::Green,
                message_system: ratatui::style::Color::DarkGray,
                status_bg: ratatui::style::Color::Rgb(18, 40, 60),
                status_fg: ratatui::style::Color::Rgb(200, 220, 240),
            },
        }
    }
}
