#!/usr/bin/env bash
# PS-1: write PLAN_STATUS.md — one row per plan ID in NEXT_PLAN_TASKS.md's wave
# tables (§R-1), with what the plan file marks for it and which commits name it.
#
# Nothing here is typed by hand, so the counts cannot drift from the two things
# they are read from. Run from the repository root:
#
#     scripts/plan-status.sh            # rewrites PLAN_STATUS.md
#     scripts/plan-status.sh --check    # exits 1 if PLAN_STATUS.md is out of date
set -euo pipefail

plan="NEXT_PLAN_TASKS.md"
out="PLAN_STATUS.md"
[ -f "$plan" ] || { echo "run from the repository root: $plan not found" >&2; exit 2; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Wave rows: "WAVE<TAB>ID<TAB>ITEM<TAB>BUCKET", in file order, from §R-1 only.
awk '
  /^### R-1 The waves/ { inside = 1; next }
  /^### R-2 /          { inside = 0 }
  !inside              { next }
  /^#### (W[0-9]+|Not scheduled) / {
      line = $0; sub(/^#### /, "", line)
      if (line ~ /progress/) { next }
      wave = line; sub(/ .*/, "", wave)
      if (line ~ /^Not scheduled/) { wave = "unscheduled" }
      next
  }
  /^\| \*\*[A-Za-z]+-[0-9]+[a-z]?\*\* \|/ {
      n = split($0, cell, "|")
      id = cell[2]; gsub(/[* ]/, "", id)
      item = cell[3]; gsub(/^ +| +$/, "", item)
      bucket = cell[4]; gsub(/^ +| +$/, "", bucket)
      printf "%s\t%s\t%s\t%s\n", wave, id, item, bucket
  }
' "$plan" > "$tmp/rows.tsv"

git log --format='%h%x09%ad%x09%s' --date=short > "$tmp/log.tsv"

# For each ID: what the plan marks, and the commits that name it in their subject.
while IFS=$'\t' read -r wave id item bucket; do
  esc="${id//./\\.}"
  marked_done=$(grep -cE "^\s*- \[x\].{0,120}\b${esc}\b" "$plan" || true)
  marked_open=$(grep -cE "^\s*- \[ \].{0,120}\b${esc}\b" "$plan" || true)
  if [ "$marked_done" -gt 0 ] && [ "$marked_open" -gt 0 ]; then mark="both"
  elif [ "$marked_done" -gt 0 ]; then mark="done"
  elif [ "$marked_open" -gt 0 ]; then mark="open"
  else mark="—"; fi
  commits=$(awk -F'\t' -v id="$esc" '$3 ~ ("(^|[^A-Za-z0-9-])" id "([^0-9]|$)")' "$tmp/log.tsv")
  count=$(printf '%s' "$commits" | grep -c . || true)
  latest=$(printf '%s\n' "$commits" | head -1 | awk -F'\t' 'NF { print $1 " (" $2 ")" }')
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$wave" "$id" "$item" "$bucket" "$mark" "$count" "${latest:-—}"
done < "$tmp/rows.tsv" > "$tmp/status.tsv"

{
  echo "# Plan status"
  echo
  echo "> Generated by \`scripts/plan-status.sh\` from the wave tables in"
  echo "> [NEXT_PLAN_TASKS.md](NEXT_PLAN_TASKS.md) (§R-1) and \`git log\`. Do not edit by hand —"
  echo "> run the script. **Marked** is what the plan file's own checkboxes say about the ID"
  echo "> (\`both\` means it is checked in one place and unchecked in another); **Commits** counts"
  echo "> commit subjects that name the ID. Neither is a judgement of whether the work is good."
  echo "> The current order of work is at the top of NEXT_PLAN_TASKS.md, under \"Current order\"."
  echo
  echo "## Summary"
  echo
  echo "| Wave | Rows | Marked done | Marked open | Marked both | Named by a commit |"
  echo "|---|---|---|---|---|---|"
  awk -F'\t' '
    { rows[$1]++; if ($5=="done") d[$1]++; if ($5=="open") o[$1]++; if ($5=="both") b[$1]++; if ($6>0) c[$1]++
      if (!($1 in seen)) { seen[$1]=1; order[++n]=$1 } }
    END { for (i=1;i<=n;i++) { w=order[i]; printf "| %s | %d | %d | %d | %d | %d |\n", w, rows[w], d[w], o[w], b[w], c[w]
          tr+=rows[w]; td+=d[w]; to+=o[w]; tb+=b[w]; tc+=c[w] }
          printf "| **all** | **%d** | **%d** | **%d** | **%d** | **%d** |\n", tr, td, to, tb, tc }
  ' "$tmp/status.tsv"
  current=""
  while IFS=$'\t' read -r wave id item bucket mark count latest; do
    if [ "$wave" != "$current" ]; then
      current="$wave"
      echo
      echo "## $wave"
      echo
      echo "| ID | Item | Bucket | Marked | Commits | Latest |"
      echo "|---|---|---|---|---|---|"
    fi
    printf '| %s | %s | %s | %s | %s | %s |\n' "$id" "${item//|/\\|}" "$bucket" "$mark" "$count" "$latest"
  done < "$tmp/status.tsv"
} > "$tmp/out.md"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$tmp/out.md" "$out" > /dev/null 2>&1; then
    echo "$out is out of date: run scripts/plan-status.sh" >&2
    exit 1
  fi
  echo "$out is current"
else
  mv "$tmp/out.md" "$out"
  echo "wrote $out: $(wc -l < "$tmp/status.tsv") rows"
fi
